server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.xmy.blog: info
  file:
    path: log/blog-pro.log
mybatis:
  #  type-aliases-package: com.xmy.blog
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true