server:
  port: 8080
spring:
  profiles:
    active: pro
  application:
    name: blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: xuehuafeiwu
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    com.xmy.blog: debug
  file:
    path: log/blog.log




