logging:
  level:
    root: info
    com.xmy.blog: debug
  file:
    path: log/blog-dev.log
mybatis:
  #  type-aliases-package: com.xmy.blog
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true